apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: kafka-nilrouter-subscription
spec:
  topic: {{ .Values.envValues.KAFKA_TOPIC_NAME }}
  routes:
    default: {{ .Values.envValues.KAFAKA_ROUTE }}
  pubsubname: {{ .Values.envValues.KAFAKA_PUB_SUB_NAME }}
  metadata:
    rawPayload: "true"
