apiVersion: v1
kind: ConfigMap
metadata:
  name: nil-router-configmap
data:
  port: {{ .Values.service.port | quote }}
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: {{ .Values.envValues.MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE | quote }}
  MANAGEMENT_METRICS_PROMETHEUS_ENABLED: {{ .Values.envValues.MANAGEMENT_METRICS_PROMETHEUS_ENABLED | quote }}
  SPRINGBOOT_PROMETHEUS_ENABLED: {{ .Values.envValues.SPRINGBOOT_PROMETHEUS_ENABLED | quote }}
  loglevel: {{ .Values.envValues.LOG_LEVEL }}
  datasourceUrl: {{ .Values.envValues.datasourceUrl }}
  dbusername: {{ .Values.envValues.dbusername }}
  password: {{ .Values.envValues.password }}
  diverclassname: {{ .Values.envValues.diverclassname }}
